name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check out to the master katalonTest repo
      uses: actions/checkout@v2
      with:
        repository: radhakrushna/katalonTest
        path: katalonTest
        ref: 'master'
    - name : Change the path to railways_user_api
      run: |
        cd C:\actions-runner\_work\railways_user-api\railways_user-api
    - name: list the files
      run: |
        ~/rexec.sh "cd /home/glcgadmin/;touch rk.txt"
        echo $?
        
