name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: Download the required artifacts for CI
      run: |
        ~/rexec.sh "cd /home/radha/Desktop/actions-runner/;touch rk.txt"
        echo $?
