name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check out to the master katalonTest repo
      uses: actions/checkout@v2
      with:
        repository: radhakrushna/katalonTest
        path: katalonTest
        ref: 'master'
    - name: Download the required artifacts for CI
      run: |
        ~/rexec.sh "cd /home/radha/Desktop/actions-runner/_work;ls"
        echo $?
        
